"""
Glyphlette registry and drawing sheets.

Glyphlettes are drawn by hand into TGA drawing sheets, glyphlettes/sheet_NN.tga.
Each sheet is a grid of SHEET_COLS x SHEET_ROWS cells of 16x16 px, the same cell
size as the final Han sheet. A glyphlette's box sits inside its cell exactly where
it sits in its *exemplar* character (a common character that uses it), and the
rest of the exemplar is shown around it as a guide, so every part is drawn in
context.

Pixel conventions (same as every other sheet of the font):
  ink    = opaque white-ish pixel (alpha 255, every channel >= 128)
  guides = translucent pixels (alpha < 255); they are regenerated by `refresh`
           and never mistaken for ink. Anything that is not ink is overwritten
           when guides are regenerated.

  blue tint   the box to draw in
  red tint    inside of a surround frame: keep empty, the inner part goes there
  grey tint   other parts of the exemplar that are not drawn yet
  faint white other parts of the exemplar that are already drawn

The box is where a glyphlette goes, not a limit on its ink: pixels drawn outside
it (anywhere in the cell) are kept and overlaid wherever the glyphlette is placed,
e.g. the hook of 小 reaching up through the gap to join 幺 in 糸.

A component is drawn once per family (family(): component, frame role, aspect
class); its other sizes are derived from that drawing (resize.py), unless an
override of the exact size is drawn too. The Library serves all of them.

The registry (glyphlettes/registry.tsv) assigns each issued glyphlette a
permanent cell. Cells are never reassigned: if the model changes and a
glyphlette falls out of use, its cell simply becomes an orphan.
"""

import os
from dataclasses import dataclass
from typing import Dict, List, Optional, Set, Tuple

import numpy as np

import generators as GN
import geometry as GEO
import resize as RZ
import tga
from geometry import Layout, SlotKey

HERE = os.path.dirname(os.path.abspath(__file__))
GLYPHLETTE_DIR = os.path.join(HERE, 'glyphlettes')
REGISTRY_PATH = os.path.join(GLYPHLETTE_DIR, 'registry.tsv')

SHEET_COLS = 32
SHEET_ROWS = 32
PER_SHEET = SHEET_COLS * SHEET_ROWS

COLOUR_BOX = (0x33, 0x99, 0xFF, 0x40)
COLOUR_KEEP_EMPTY = (0xFF, 0x33, 0x33, 0x30)
COLOUR_CONTEXT = (0x99, 0x99, 0x99, 0x28)
COLOUR_CONTEXT_INK = (0xFF, 0xFF, 0xFF, 0x68)
COLOUR_INK = (0xFF, 0xFF, 0xFF, 0xFF)


def ink_mask(rgba: np.ndarray) -> np.ndarray:
    return (rgba[..., 3] == 255) & (rgba[..., :3].min(axis=-1) >= 128)


class Drawing:
    """
    A drawn glyphlette: all the ink of its drawing cell, anchored at its box origin.
    Ink outside the box (protrusions) is kept and overlaid along with the rest.
    """

    def __init__(self, mask: np.ndarray, key: SlotKey, bx: int, by: int):
        self.mask = mask
        self.key = key
        self.bx, self.by = bx, by
        self._ys, self._xs = np.nonzero(mask)

    def blit(self, target: np.ndarray, x: int, y: int):
        """OR the ink into a boolean array so that the box lands at (x, y); clipped to the array."""
        ys = self._ys + (y - self.by)
        xs = self._xs + (x - self.bx)
        ok = (ys >= 0) & (ys < target.shape[0]) & (xs >= 0) & (xs < target.shape[1])
        target[ys[ok], xs[ok]] = True

    def protrusions(self) -> int:
        """Number of ink pixels outside the box."""
        m = self.mask.copy()
        m[self.by:self.by + self.key.h, self.bx:self.bx + self.key.w] = False
        return int(m.sum())


# ---------------------------------------------------------------------------
# Families: a component is drawn once per family and its other sizes are derived

# A box at least this many times taller than wide is 'tall' (a left or right part), at
# least this many times wider than tall is 'wide' (a top or bottom part), else 'square'.
# A component is drawn differently in each: 木 on the left has a dot for its last stroke,
# 木 at the bottom of 呆 spreads it wide.
FAMILY_ASPECT = 2 ** 0.5

Family = Tuple[str, str, str]


def family(key: SlotKey) -> Family:
    """(component, frame role, aspect class): the sizes that one drawing can serve."""
    if key.h >= key.w * FAMILY_ASPECT:
        aspect = 'tall'
    elif key.w >= key.h * FAMILY_ASPECT:
        aspect = 'wide'
    else:
        aspect = 'square'
    return key.comp, key.role, aspect


def is_whole(key: SlotKey) -> bool:
    return not key.role and key.w == GEO.BODY_W and key.h == GEO.BODY_H


def derivable(src: SlotKey, dst: SlotKey) -> bool:
    """Whether dst may be derived from a drawing of src: same family, and src at most
    SIZE_TOLERANCE px smaller on each axis. Whole characters are always drawn."""
    return (src != dst and family(src) == family(dst) and not is_whole(dst)
            and dst.w - src.w <= GEO.SIZE_TOLERANCE and dst.h - src.h <= GEO.SIZE_TOLERANCE)


def source_order(src: SlotKey, dst: SlotKey):
    """Sort key of the drawings a size may be derived from: the smallest one at least as
    large on both axes first (least change), then the largest of the smaller ones."""
    covers = src.w >= dst.w and src.h >= dst.h
    return (0, src.w * src.h, src.w) if covers else (1, -src.w * src.h, -src.w)


def bounding(keys) -> SlotKey:
    """The smallest size of a family that covers all of `keys`."""
    keys = list(keys)
    k = keys[0]
    return SlotKey(k.comp, max(x.w for x in keys), max(x.h for x in keys), k.role)


class Library:
    """
    Every glyphlette the assembler can use, in order of preference:
      drawn      a hand drawing of exactly this slot
      generated  a procedural glyphlette (generators.py)
      derived    resized from the closest hand drawing of its family (resize.py);
                 if that one declines, the next closest is tried
    Behaves like a read-only mapping from slot keys to drawings.
    """

    def __init__(self, hand: Dict[SlotKey, Drawing], layout: Layout, cache: 'RZ.Cache' = None):
        self.hand = hand
        self.layout = layout
        self.cache = cache
        self._by_family: Dict[Family, List[SlotKey]] = {}
        for k in hand:
            self._by_family.setdefault(family(k), []).append(k)
        self._cache: Dict[SlotKey, Tuple] = {}
        self._derived: Dict[Tuple[SlotKey, SlotKey], Optional[RZ.Derived]] = {}

    def sources(self, key: SlotKey) -> List[SlotKey]:
        """Hand drawings `key` may be derived from, best first."""
        return sorted((k for k in self._by_family.get(family(key), ()) if derivable(k, key)),
                      key=lambda k: source_order(k, key))

    def derive(self, src: SlotKey, key: SlotKey) -> Optional[RZ.Derived]:
        """The drawing of `src` resized to `key` (ok or declined), or None if it cannot be mapped."""
        hit = self._derived.get((src, key), False)
        if hit is not False:
            return hit
        d = self.hand[src]
        insets = new_insets = None
        if key.role:
            insets = self.layout.insets(src.comp, src.role, src.w, src.h)
            new_insets = self.layout.insets(key.comp, key.role, key.w, key.h)
        args = (d.bx, d.by, src.w, src.h, key.w, key.h, insets, new_insets)
        ck = self.cache.key(d.mask, *args) if self.cache else None
        hit = self.cache.get(ck) if self.cache else False
        if hit is False:
            hit = RZ.derive(d.mask, *args)
            if self.cache:
                self.cache.put(ck, hit)
        self._derived[(src, key)] = hit
        return hit

    def derivation(self, key: SlotKey) -> Tuple[Optional[SlotKey], Optional[RZ.Derived], List[SlotKey]]:
        """(source, result, sources that declined) of the best derivation of `key`.
        With no acceptable one, the result is the draft of the closest source."""
        declined, draft = [], (None, None)
        for src in self.sources(key):
            d = self.derive(src, key)
            if d is None:
                continue
            if d.ok:
                return src, d, declined
            declined.append(src)
            if draft[1] is None:
                draft = (src, d)
        return draft[0], draft[1], declined

    def lookup(self, key: SlotKey):
        """Returns (drawing, kind, source key) or None."""
        hit = self._cache.get(key)
        if hit is None and key not in self._cache:
            hit = self._lookup(key)
            self._cache[key] = hit
        return hit

    def _lookup(self, key: SlotKey):
        d = self.hand.get(key)
        if d is not None:
            return d, 'drawn', key
        g = GN.generate_for(self.layout, key)
        if g is not None:
            mask = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
            mask[:key.h, :key.w] = g
            return Drawing(mask, key, 0, 0), 'generated', key
        src, d, _ = self.derivation(key)
        if d is not None and d.ok:
            return Drawing(d.mask, key, d.bx, d.by), 'derived', src
        return None

    def __contains__(self, key) -> bool:
        return self.lookup(key) is not None

    def __getitem__(self, key):
        hit = self.lookup(key)
        if hit is None:
            raise KeyError(key)
        return hit[0]

    def kind(self, key: SlotKey):
        hit = self.lookup(key)
        return hit[1] if hit else None

    def source(self, key: SlotKey):
        hit = self.lookup(key)
        return hit[2] if hit else None

    def derive_ok(self, src: SlotKey, key: SlotKey) -> Optional[bool]:
        """For the planner: whether `key` derives acceptably from `src`; None if `src` is not drawn yet."""
        if src not in self.hand:
            return None
        d = self.derive(src, key)
        return d is not None and d.ok


BODY_MASK = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
BODY_MASK[GEO.BODY_Y:GEO.BODY_Y + GEO.BODY_H, GEO.BODY_X:GEO.BODY_X + GEO.BODY_W] = True


def compose(placements, drawn: Dict[SlotKey, Drawing]) -> np.ndarray:
    """Overlay the drawings of placed glyphlettes into one cell, clipped to the body."""
    cell = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
    for key, x, y in placements:
        drawn[key].blit(cell, x, y)
    return cell & BODY_MASK


@dataclass
class Entry:
    id: int
    key: SlotKey
    bx: int           # box origin inside the cell
    by: int
    exemplar: str     # character whose layout provides the context

    @property
    def sheet(self) -> int:
        return self.id // PER_SHEET

    @property
    def col(self) -> int:
        return self.id % SHEET_COLS

    @property
    def row(self) -> int:
        return (self.id % PER_SHEET) // SHEET_COLS

    @property
    def cell_origin(self) -> Tuple[int, int]:
        return self.col * GEO.CELL_W, self.row * GEO.CELL_H


def sheet_path(n: int) -> str:
    return os.path.join(GLYPHLETTE_DIR, f"sheet_{n:02d}.tga")


class Registry:
    HEADER = (
        "# Juxing glyphlette registry -- one line per issued glyphlette, in cell order.\n"
        "# Written by `juxing.py issue`. Cells are permanent: never renumber or delete lines.\n"
        "# A retired cell (`juxing.py retire`) keeps its line, with '-' for the glyphlette, and is\n"
        "# given to the next glyphlette issued.\n"
        "# id = cell number (sheet = id // %d, row-major within the sheet)\n"
        "#id\tglyphlette\tbox_x\tbox_y\texemplar\n" % PER_SHEET
    )

    def __init__(self, path=REGISTRY_PATH):
        self.path = path
        self.entries: List[Entry] = []          # the cells in use, in id order
        self.by_key: Dict[SlotKey, Entry] = {}
        self.by_id: Dict[int, Entry] = {}
        self.retired: Set[int] = set()          # cells given up, free for the next issue
        if os.path.exists(path):
            with open(path, encoding='utf-8') as f:
                for line in f:
                    if line.startswith('#') or not line.strip():
                        continue
                    i, key, bx, by, ex = (line.rstrip('\n').split('\t') + [''] * 5)[:5]
                    if key == '-':
                        self._check_id(int(i))
                        self.retired.add(int(i))
                    else:
                        self._add(Entry(int(i), SlotKey.parse(key), int(bx), int(by), ex))

    @property
    def size(self) -> int:
        """Cells allotted so far, in use or retired."""
        return len(self.entries) + len(self.retired)

    def _check_id(self, i: int):
        if i != self.size:
            raise ValueError(f"{self.path}: registry ids must be consecutive (found {i})")

    def _add(self, e: Entry):
        self._check_id(e.id)
        if e.key in self.by_key:
            raise ValueError(f"{self.path}: {e.key} issued twice")
        self.entries.append(e)
        self.by_key[e.key] = e
        self.by_id[e.id] = e

    def save(self):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        lines = {e.id: f"{e.id}\t{e.key}\t{e.bx}\t{e.by}\t{e.exemplar}\n" for e in self.entries}
        lines.update({i: f"{i}\t-\t-\t-\t-\n" for i in self.retired})
        with open(self.path + '.part', 'w', encoding='utf-8', newline='\n') as f:
            f.write(self.HEADER)
            for i in sorted(lines):
                f.write(lines[i])
        os.replace(self.path + '.part', self.path)

    def next_id(self) -> int:
        """The cell the next glyphlette issued gets: the first retired one, else a new one."""
        return min(self.retired) if self.retired else self.size

    def issue(self, key: SlotKey, bx: int, by: int, exemplar: str) -> Entry:
        if key in self.by_key:
            raise ValueError(f"{key} is already issued")
        e = Entry(self.next_id(), key, bx, by, exemplar)
        if e.id in self.retired:
            self.retired.discard(e.id)
            self.entries.append(e)
            self.entries.sort(key=lambda x: x.id)
            self.by_key[key] = e
            self.by_id[e.id] = e
        else:
            self._add(e)
        return e

    def retire(self, e: Entry):
        """Give a cell up: it keeps its number (nothing moves) and goes to the next glyphlette
        issued. Its ink is the caller's to clear (juxing.retire)."""
        self.entries.remove(e)
        del self.by_key[e.key]
        del self.by_id[e.id]
        self.retired.add(e.id)

    def on_sheet(self, n: int) -> List[Entry]:
        return [e for e in self.entries if e.sheet == n]

    def sheet_count(self) -> int:
        return (self.size + PER_SHEET - 1) // PER_SHEET


# ---------------------------------------------------------------------------
# Locating a glyphlette inside its exemplar

def cut_placements(layout: Layout, cp: int, is_leaf) -> List[Tuple[SlotKey, int, int]]:
    """All leaf placements of a character's layout, cutting where is_leaf(key) holds."""
    out = []

    def walk(key, x, y):
        s = layout.slot(key)
        if is_leaf(key) or s.parts is None:
            out.append((key, x, y))
            return
        for c, dx, dy in s.parts:
            walk(c, x + dx, y + dy)

    walk(layout.root(cp), GEO.BODY_X, GEO.BODY_Y)
    return out


def pick_exemplar(layout: Layout, key: SlotKey, users: List[int], is_leaf) -> Tuple[str, int, int]:
    """
    Choose the exemplar for a glyphlette among the characters using it: the most
    common one, and among those the one with the fewest parts, so the glyphlette
    is shown in its most typical position. Returns (char, box x, box y).
    """
    model = layout.model
    best = None
    for cp in users:
        pl = cut_placements(layout, cp, is_leaf)
        for k, x, y in pl:
            if k == key:
                rank = (model[chr(cp)].tier, len(pl), cp < 0x4E00, cp)
                if best is None or rank < best[0]:
                    best = (rank, chr(cp), x, y)
                break
    if best:
        return best[1:]
    # not part of any planned character: centre it vertically in the body
    return '', GEO.BODY_X, GEO.BODY_Y + (GEO.BODY_H - key.h) // 2


# ---------------------------------------------------------------------------
# Sheets

class Sheets:
    """Lazy access to the drawing sheets."""

    def __init__(self, registry: Registry):
        self.registry = registry
        self._images: Dict[int, np.ndarray] = {}

    def image(self, n: int) -> np.ndarray:
        img = self._images.get(n)
        if img is None:
            path = sheet_path(n)
            if os.path.exists(path):
                img = tga.read(path)
                want = (SHEET_ROWS * GEO.CELL_H, SHEET_COLS * GEO.CELL_W)
                if img.shape[:2] != want:
                    raise ValueError(f"{path}: expected {want[1]}x{want[0]} px, got {img.shape[1]}x{img.shape[0]}")
            else:
                img = np.zeros((SHEET_ROWS * GEO.CELL_H, SHEET_COLS * GEO.CELL_W, 4), dtype=np.uint8)
            self._images[n] = img
        return img

    def cell(self, e: Entry) -> np.ndarray:
        cx, cy = e.cell_origin
        return self.image(e.sheet)[cy:cy + GEO.CELL_H, cx:cx + GEO.CELL_W]

    def drawing(self, e: Entry) -> Drawing:
        return Drawing(ink_mask(self.cell(e)), e.key, e.bx, e.by)

    def drawn(self) -> Dict[SlotKey, Drawing]:
        out = {}
        for e in self.registry.entries:
            if not os.path.exists(sheet_path(e.sheet)):
                continue
            d = self.drawing(e)
            if d.mask.any():
                out[e.key] = d
        return out

    def render_guides(self, n: int, layout: Layout, is_leaf, drawn: Dict[SlotKey, Drawing]) -> np.ndarray:
        """Regenerate the guide pixels of sheet n, keeping its ink."""
        old = self.image(n)
        keep = ink_mask(old)
        img = np.zeros_like(old)
        first = n * PER_SHEET
        for e in self.registry.on_sheet(n):
            cx, cy = e.cell_origin
            cell = img[cy:cy + GEO.CELL_H, cx:cx + GEO.CELL_W]
            _paint_cell(cell, e, layout, is_leaf, drawn)
        img[keep] = old[keep]
        self._images[n] = img
        return img

    def save(self, n: int):
        os.makedirs(GLYPHLETTE_DIR, exist_ok=True)
        tga.write(sheet_path(n), self.image(n))


def _fill(cell, x, y, w, h, colour):
    cell[max(y, 0):y + h, max(x, 0):x + w] = colour


def _frame_inner(layout: Layout, key: SlotKey) -> Tuple[int, int, int, int]:
    l, t, r, b = layout.insets(key.comp, key.role, key.w, key.h)
    return l, t, key.w - l - r, key.h - t - b


Rect = Tuple[int, int, int, int]   # x, y, w, h


@dataclass
class Guides:
    """What the guides of a drawing cell show (cell coordinates)."""
    box: Rect                                        # where the glyphlette goes
    keep_empty: Optional[Rect]                       # inside of a frame
    context: List[Tuple[SlotKey, Rect, Optional[Rect]]]   # undrawn parts of the exemplar (and a frame's inside)
    context_ink: np.ndarray                          # drawn parts of the exemplar, protrusions included


def cell_guides(e: Entry, layout: Layout, is_leaf, drawn) -> Guides:
    context = []
    if e.exemplar:
        context = [(k, x, y) for k, x, y in
                   cut_placements(layout, ord(e.exemplar), lambda k: k == e.key or is_leaf(k))
                   if not (k == e.key and (x, y) == (e.bx, e.by))]
    parts = []
    ink = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
    for k, x, y in context:
        if k in drawn:
            drawn[k].blit(ink, x, y)
            continue
        hole = None
        if k.role:
            ix, iy, iw, ih = _frame_inner(layout, k)
            hole = (x + ix, y + iy, iw, ih)
        parts.append((k, (x, y, k.w, k.h), hole))
    keep = None
    if e.key.role:
        ix, iy, iw, ih = _frame_inner(layout, e.key)
        keep = (e.bx + ix, e.by + iy, iw, ih)
    return Guides((e.bx, e.by, e.key.w, e.key.h), keep, parts, ink & BODY_MASK)


def _paint_cell(cell, e: Entry, layout: Layout, is_leaf, drawn: Dict[SlotKey, Drawing]):
    g = cell_guides(e, layout, is_leaf, drawn)
    # parts of the exemplar that are not drawn yet
    for _, rect, hole in g.context:
        _fill(cell, *rect, COLOUR_CONTEXT)
        if hole:
            _fill(cell, *hole, (0, 0, 0, 0))
    # the box itself
    _fill(cell, *g.box, COLOUR_BOX)
    if g.keep_empty:
        _fill(cell, *g.keep_empty, COLOUR_KEEP_EMPTY)
    # parts that are drawn, protrusions included, over everything
    cell[g.context_ink] = COLOUR_CONTEXT_INK
