"""
Glyphlette registry and drawing sheets.

Glyphlettes are drawn by hand into TGA drawing sheets, glyphlettes/sheet_NN.tga.
Each sheet is a grid of SHEET_COLS x SHEET_ROWS cells of 16x16 px, the same cell
size as the final Han sheet. A glyphlette's box sits inside its cell exactly where
it sits in its *exemplar* character (a common character that uses it), and the
rest of the exemplar is shown around it as a guide, so every part is drawn in
context.

Pixel conventions (same as every other sheet of the font):
  ink    = opaque white-ish pixel (alpha 255, every channel >= 128)
  guides = translucent pixels (alpha < 255); they are regenerated by `refresh`
           and never mistaken for ink. Anything that is not ink is overwritten
           when guides are regenerated.

  blue tint   the box to draw in
  red tint    inside of a surround frame: keep empty, the inner part goes there
  grey tint   other parts of the exemplar that are not drawn yet
  faint white other parts of the exemplar that are already drawn

The box is where a glyphlette goes, not a limit on its ink: pixels drawn outside
it (anywhere in the cell) are kept and overlaid wherever the glyphlette is placed,
e.g. the hook of 小 reaching up through the gap to join 幺 in 糸.

The registry (glyphlettes/registry.tsv) assigns each issued glyphlette a
permanent cell. Cells are never reassigned: if the model changes and a
glyphlette falls out of use, its cell simply becomes an orphan.
"""

import os
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np

import generators as GN
import geometry as GEO
import tga
from geometry import Layout, SlotKey

HERE = os.path.dirname(os.path.abspath(__file__))
GLYPHLETTE_DIR = os.path.join(HERE, 'glyphlettes')
REGISTRY_PATH = os.path.join(GLYPHLETTE_DIR, 'registry.tsv')

SHEET_COLS = 32
SHEET_ROWS = 32
PER_SHEET = SHEET_COLS * SHEET_ROWS

COLOUR_BOX = (0x33, 0x99, 0xFF, 0x40)
COLOUR_KEEP_EMPTY = (0xFF, 0x33, 0x33, 0x30)
COLOUR_CONTEXT = (0x99, 0x99, 0x99, 0x28)
COLOUR_CONTEXT_INK = (0xFF, 0xFF, 0xFF, 0x68)
COLOUR_INK = (0xFF, 0xFF, 0xFF, 0xFF)


def ink_mask(rgba: np.ndarray) -> np.ndarray:
    return (rgba[..., 3] == 255) & (rgba[..., :3].min(axis=-1) >= 128)


class Drawing:
    """
    A drawn glyphlette: all the ink of its drawing cell, anchored at its box origin.
    Ink outside the box (protrusions) is kept and overlaid along with the rest.
    """

    def __init__(self, mask: np.ndarray, key: SlotKey, bx: int, by: int):
        self.mask = mask
        self.key = key
        self.bx, self.by = bx, by
        self._ys, self._xs = np.nonzero(mask)

    def blit(self, target: np.ndarray, x: int, y: int):
        """OR the ink into a boolean array so that the box lands at (x, y); clipped to the array."""
        ys = self._ys + (y - self.by)
        xs = self._xs + (x - self.bx)
        ok = (ys >= 0) & (ys < target.shape[0]) & (xs >= 0) & (xs < target.shape[1])
        target[ys[ok], xs[ok]] = True

    def protrusions(self) -> int:
        """Number of ink pixels outside the box."""
        m = self.mask.copy()
        m[self.by:self.by + self.key.h, self.bx:self.bx + self.key.w] = False
        return int(m.sum())


class Shifted:
    """A drawing reused for a slot up to SIZE_TOLERANCE px larger, centred in it."""

    def __init__(self, drawing: Drawing, dx: int, dy: int):
        self.drawing, self.dx, self.dy = drawing, dx, dy
        self.key = drawing.key

    def blit(self, target: np.ndarray, x: int, y: int):
        self.drawing.blit(target, x + self.dx, y + self.dy)

    def protrusions(self) -> int:
        return self.drawing.protrusions()


def reusable_for(drawn: SlotKey, slot: SlotKey) -> bool:
    """Whether a drawing of `drawn` may serve `slot` (same component, slot up to SIZE_TOLERANCE larger)."""
    return (drawn.comp == slot.comp and not drawn.role and not slot.role
            and not (slot.w == GEO.BODY_W and slot.h == GEO.BODY_H)
            and 0 <= slot.w - drawn.w <= GEO.SIZE_TOLERANCE and 0 <= slot.h - drawn.h <= GEO.SIZE_TOLERANCE)


class Library:
    """
    Every glyphlette the assembler can use, in order of preference:
      drawn      a hand drawing of exactly this slot
      generated  a procedural glyphlette (generators.py)
      reused     a hand drawing of the same component up to SIZE_TOLERANCE px smaller,
                 centred in the slot
    Behaves like a read-only mapping from slot keys to drawings.
    """

    def __init__(self, hand: Dict[SlotKey, Drawing], layout: Layout):
        self.hand = hand
        self.layout = layout
        self._by_comp: Dict[str, List[SlotKey]] = {}
        for k in hand:
            if not k.role:
                self._by_comp.setdefault(k.comp, []).append(k)
        self._cache: Dict[SlotKey, Tuple] = {}

    def lookup(self, key: SlotKey):
        """Returns (drawing, kind, source key) or None."""
        hit = self._cache.get(key)
        if hit is None and key not in self._cache:
            hit = self._lookup(key)
            self._cache[key] = hit
        return hit

    def _lookup(self, key: SlotKey):
        d = self.hand.get(key)
        if d is not None:
            return d, 'drawn', key
        g = GN.generate_for(self.layout, key)
        if g is not None:
            mask = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
            mask[:key.h, :key.w] = g
            return Drawing(mask, key, 0, 0), 'generated', key
        best = None
        for k in self._by_comp.get(key.comp, ()):
            if reusable_for(k, key) and (best is None or (k.w * k.h, k.w) > (best.w * best.h, best.w)):
                best = k
        if best is not None:
            return Shifted(self.hand[best], (key.w - best.w) // 2, (key.h - best.h) // 2), 'reused', best
        return None

    def __contains__(self, key) -> bool:
        return self.lookup(key) is not None

    def __getitem__(self, key):
        hit = self.lookup(key)
        if hit is None:
            raise KeyError(key)
        return hit[0]

    def kind(self, key: SlotKey):
        hit = self.lookup(key)
        return hit[1] if hit else None

    def source(self, key: SlotKey):
        hit = self.lookup(key)
        return hit[2] if hit else None


BODY_MASK = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
BODY_MASK[GEO.BODY_Y:GEO.BODY_Y + GEO.BODY_H, GEO.BODY_X:GEO.BODY_X + GEO.BODY_W] = True


def compose(placements, drawn: Dict[SlotKey, Drawing]) -> np.ndarray:
    """Overlay the drawings of placed glyphlettes into one cell, clipped to the body."""
    cell = np.zeros((GEO.CELL_H, GEO.CELL_W), dtype=bool)
    for key, x, y in placements:
        drawn[key].blit(cell, x, y)
    return cell & BODY_MASK


@dataclass
class Entry:
    id: int
    key: SlotKey
    bx: int           # box origin inside the cell
    by: int
    exemplar: str     # character whose layout provides the context

    @property
    def sheet(self) -> int:
        return self.id // PER_SHEET

    @property
    def col(self) -> int:
        return self.id % SHEET_COLS

    @property
    def row(self) -> int:
        return (self.id % PER_SHEET) // SHEET_COLS

    @property
    def cell_origin(self) -> Tuple[int, int]:
        return self.col * GEO.CELL_W, self.row * GEO.CELL_H


def sheet_path(n: int) -> str:
    return os.path.join(GLYPHLETTE_DIR, f"sheet_{n:02d}.tga")


class Registry:
    HEADER = (
        "# Juxing glyphlette registry -- one line per issued glyphlette, in cell order.\n"
        "# Written by `juxing.py issue`. Cells are permanent: never renumber or delete lines.\n"
        "# id = cell number (sheet = id // %d, row-major within the sheet)\n"
        "#id\tglyphlette\tbox_x\tbox_y\texemplar\n" % PER_SHEET
    )

    def __init__(self, path=REGISTRY_PATH):
        self.path = path
        self.entries: List[Entry] = []
        self.by_key: Dict[SlotKey, Entry] = {}
        if os.path.exists(path):
            with open(path, encoding='utf-8') as f:
                for line in f:
                    if line.startswith('#') or not line.strip():
                        continue
                    i, key, bx, by, ex = line.rstrip('\n').split('\t')
                    self._add(Entry(int(i), SlotKey.parse(key), int(bx), int(by), ex))

    def _add(self, e: Entry):
        if e.id != len(self.entries):
            raise ValueError(f"{self.path}: registry ids must be consecutive (found {e.id})")
        if e.key in self.by_key:
            raise ValueError(f"{self.path}: {e.key} issued twice")
        self.entries.append(e)
        self.by_key[e.key] = e

    def save(self):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        with open(self.path + '.part', 'w', encoding='utf-8', newline='\n') as f:
            f.write(self.HEADER)
            for e in self.entries:
                f.write(f"{e.id}\t{e.key}\t{e.bx}\t{e.by}\t{e.exemplar}\n")
        os.replace(self.path + '.part', self.path)

    def issue(self, key: SlotKey, bx: int, by: int, exemplar: str) -> Entry:
        e = Entry(len(self.entries), key, bx, by, exemplar)
        self._add(e)
        return e

    def sheet_count(self) -> int:
        return (len(self.entries) + PER_SHEET - 1) // PER_SHEET


# ---------------------------------------------------------------------------
# Locating a glyphlette inside its exemplar

def cut_placements(layout: Layout, cp: int, is_leaf) -> List[Tuple[SlotKey, int, int]]:
    """All leaf placements of a character's layout, cutting where is_leaf(key) holds."""
    out = []

    def walk(key, x, y):
        s = layout.slot(key)
        if is_leaf(key) or s.parts is None:
            out.append((key, x, y))
            return
        for c, dx, dy in s.parts:
            walk(c, x + dx, y + dy)

    walk(layout.root(cp), GEO.BODY_X, GEO.BODY_Y)
    return out


def pick_exemplar(layout: Layout, key: SlotKey, users: List[int], is_leaf) -> Tuple[str, int, int]:
    """
    Choose the exemplar for a glyphlette among the characters using it: the most
    common one, and among those the one with the fewest parts, so the glyphlette
    is shown in its most typical position. Returns (char, box x, box y).
    """
    model = layout.model
    best = None
    for cp in users:
        pl = cut_placements(layout, cp, is_leaf)
        for k, x, y in pl:
            if k == key:
                rank = (model[chr(cp)].tier, len(pl), cp < 0x4E00, cp)
                if best is None or rank < best[0]:
                    best = (rank, chr(cp), x, y)
                break
    if best:
        return best[1:]
    # not part of any planned character: centre it vertically in the body
    return '', GEO.BODY_X, GEO.BODY_Y + (GEO.BODY_H - key.h) // 2


# ---------------------------------------------------------------------------
# Sheets

class Sheets:
    """Lazy access to the drawing sheets."""

    def __init__(self, registry: Registry):
        self.registry = registry
        self._images: Dict[int, np.ndarray] = {}

    def image(self, n: int) -> np.ndarray:
        img = self._images.get(n)
        if img is None:
            path = sheet_path(n)
            if os.path.exists(path):
                img = tga.read(path)
                want = (SHEET_ROWS * GEO.CELL_H, SHEET_COLS * GEO.CELL_W)
                if img.shape[:2] != want:
                    raise ValueError(f"{path}: expected {want[1]}x{want[0]} px, got {img.shape[1]}x{img.shape[0]}")
            else:
                img = np.zeros((SHEET_ROWS * GEO.CELL_H, SHEET_COLS * GEO.CELL_W, 4), dtype=np.uint8)
            self._images[n] = img
        return img

    def cell(self, e: Entry) -> np.ndarray:
        cx, cy = e.cell_origin
        return self.image(e.sheet)[cy:cy + GEO.CELL_H, cx:cx + GEO.CELL_W]

    def drawing(self, e: Entry) -> Drawing:
        return Drawing(ink_mask(self.cell(e)), e.key, e.bx, e.by)

    def drawn(self) -> Dict[SlotKey, Drawing]:
        out = {}
        for e in self.registry.entries:
            if not os.path.exists(sheet_path(e.sheet)):
                continue
            d = self.drawing(e)
            if d.mask.any():
                out[e.key] = d
        return out

    def render_guides(self, n: int, layout: Layout, is_leaf, drawn: Dict[SlotKey, Drawing]) -> np.ndarray:
        """Regenerate the guide pixels of sheet n, keeping its ink."""
        old = self.image(n)
        keep = ink_mask(old)
        img = np.zeros_like(old)
        first = n * PER_SHEET
        for e in self.registry.entries[first:first + PER_SHEET]:
            cx, cy = e.cell_origin
            cell = img[cy:cy + GEO.CELL_H, cx:cx + GEO.CELL_W]
            _paint_cell(cell, e, layout, is_leaf, drawn)
        img[keep] = old[keep]
        self._images[n] = img
        return img

    def save(self, n: int):
        os.makedirs(GLYPHLETTE_DIR, exist_ok=True)
        tga.write(sheet_path(n), self.image(n))


def _fill(cell, x, y, w, h, colour):
    cell[max(y, 0):y + h, max(x, 0):x + w] = colour


def _frame_inner(layout: Layout, key: SlotKey) -> Tuple[int, int, int, int]:
    l, t, r, b = layout.insets(key.comp, key.role, key.w, key.h)
    return l, t, key.w - l - r, key.h - t - b


def _paint_cell(cell, e: Entry, layout: Layout, is_leaf, drawn: Dict[SlotKey, Drawing]):
    context = []
    if e.exemplar:
        context = [(k, x, y) for k, x, y in
                   cut_placements(layout, ord(e.exemplar), lambda k: k == e.key or is_leaf(k))
                   if not (k == e.key and (x, y) == (e.bx, e.by))]
    # parts of the exemplar that are not drawn yet
    for k, x, y in context:
        if k in drawn:
            continue
        _fill(cell, x, y, k.w, k.h, COLOUR_CONTEXT)
        if k.role:
            ix, iy, iw, ih = _frame_inner(layout, k)
            _fill(cell, x + ix, y + iy, iw, ih, (0, 0, 0, 0))
    # the box itself
    _fill(cell, e.bx, e.by, e.key.w, e.key.h, COLOUR_BOX)
    if e.key.role:
        ix, iy, iw, ih = _frame_inner(layout, e.key)
        _fill(cell, e.bx + ix, e.by + iy, iw, ih, COLOUR_KEEP_EMPTY)
    # parts that are drawn, protrusions included, over everything
    ink = np.zeros(cell.shape[:2], dtype=bool)
    for k, x, y in context:
        if k in drawn:
            drawn[k].blit(ink, x, y)
    cell[ink & BODY_MASK] = COLOUR_CONTEXT_INK
